const errorCodes = {
  UNKNOWN_ERROR: 0,
  EXCEPTION: 1,
  INTERNAL_SERVER_ERROR: 2,
  INVALID_URL: 3,
  INPUT_PARAMS_INVALID: 4,
  EMAIL_ALREADY_EXISTS: 5,
  CONTACT_ALREADY_EXISTS: 6,
  INVALID_EMAIL_OR_PASSWORD: 7,
  INVALID_TOKEN: 8,
  EVENT_ID_NOT_FOUND: 9,
  USER_NOT_AUTHORIZED: 10,
  USER_ALREADY_REGISTERED: 11,
  USER_NOT_REGISTERED: 12,
  EVENT_EXPIRED: 13,
  EVENT_FULL: 14,
  USER_REGISTERING_FOR_OWN_EVENT: 15,
  EVENT_HAS_REGISTRATIONS: 16,
};

const imageTypes = {
  USER_IMAGE: 0,
  EVENT_IMAGE: 1,
};

module.exports = {
  errorCodes,
  imageTypes,
};
